# use Node.js
FROM node:18-alpine

# set working directory
WORKDIR /app-frontend/

# copy needed files into the working directory
COPY public/ /app-frontend/public
COPY src/ /app-frontend/src
COPY package.json /app-frontend/

# install npm and un
RUN npm install

# command that will be executed after the container's start
CMD ["npm", "start"]