version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose backend on port 8080
    networks:
      - app-network
      
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile  
    ports:
      - "8000:3000"  # Expose frontend on port 8000
    networks:
      - app-network
    depends_on:
      - backend  # Ensure backend is started first

networks:
  app-network:
    driver: bridge
